from pyautogui import size
import math

# SCREEN SIZE
WIDTH_SCREEN, HEIGHT_SCREEN = size()
WIDTH_SCREEN = math.floor(WIDTH_SCREEN * 0.4)
HEIGHT_SCREEN = math.floor(HEIGHT_SCREEN * 0.8)

# FIELD SIZE
WIDTH_FIELD = WIDTH_SCREEN * 0.45
WIDTH_FIELD = WIDTH_FIELD // 10 * 10
HEIGHT_FIELD = WIDTH_FIELD * 2
COLUMNS = 10
ROWS = 20

# PIECE
BLOCK_DIMENSION = WIDTH_FIELD// 10

# SURFACES COLOR
MAIN_SCREEN_SURFACE_COLOR = (0,0,0)
FIELD_SURFACE_COLOR = (25,123,0)
LINE_SURFACE_COLOR = (0,255,0)
LINE_SURFACE_ALPHA = 120
LINE_COLOR = (50,50,50)